name: fittrack
description: A Flutter fitness tracker app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  intl: ^0.18.1
  uuid: ^3.0.7
  google_fonts: ^5.1.0

  # --- NEW PACKAGES FOR NOTIFICATIONS ---
  flutter_local_notifications: ^16.3.0
  flutter_timezone: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: false
  adaptive_icon_background: "assets/logo/logo_background.png"
  adaptive_icon_foreground: "assets/logo/logo_foreground.png"
  image_path: "assets/logo/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
