name: Build FitTrack Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Recreate platform-specific files
        run: flutter create --org dev.sleepy --platforms=android .
      
      # --- NEW, ROBUST STRATEGY FOR ANDROID MANIFEST ---
      - name: Prepare Android Manifest from Template
        run: |
          MANIFEST_PATH="android/app/src/main/AndroidManifest.xml"
          # Copy our reliable template over the generated one
          cp ci_templates/AndroidManifest.template.xml $MANIFEST_PATH
          
          # Replace the app label placeholder
          sed -i 's/__APP_LABEL__/FitTrack/g' $MANIFEST_PATH

          # Replace the notification permissions placeholder
          PERMISSIONS='    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />\n    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />'
          sed -i "s|<!-- __NOTIFICATION_PERMISSIONS__ -->|$PERMISSIONS|g" $MANIFEST_PATH

          # Replace the notification receivers placeholder
          RECEIVERS='        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" \/>\n        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">\n            <intent-filter>\n                <action android:name="android.intent.action.BOOT_COMPLETED" \/>\n                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" \/>\n                <action android:name="android.intent.action.QUICKBOOT_POWERON" \/>\n                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON" \/>\n            <\/intent-filter>\n        <\/receiver>'
          sed -i "s|<!-- __NOTIFICATION_RECEIVERS__ -->|$RECEIVERS|g" $MANIFEST_PATH

      # Fix NDK version in build.gradle
      - name: Fix NDK version
        run: echo "android.ndkVersion = \"27.0.12077973\"" >> android/app/build.gradle.kts
      
      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons

      - name: Run Hive generator
        run: flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Build Universal APK
        run: flutter build apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fittrack-universal-apk
          path: build/app/outputs/flutter-apk/app-release.apk
